name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: chmod
      run: chmod +x test.sh
    - name: make
      run: make
    - name: make test
      run: make test
